# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import catalogo_pb2 as catalogo__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in catalogo_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CatalogoStub:
    """Servicio gRPC para la gestion del catalogo de la biblioteca y reserva de ejemplares.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ConsultarDisponibilidad = channel.unary_unary(
                '/catalogo.Catalogo/ConsultarDisponibilidad',
                request_serializer=catalogo__pb2.ConsultaRequest.SerializeToString,
                response_deserializer=catalogo__pb2.ConsultaResponse.FromString,
                _registered_method=True)
        self.ReservarEjemplar = channel.unary_unary(
                '/catalogo.Catalogo/ReservarEjemplar',
                request_serializer=catalogo__pb2.ReservaRequest.SerializeToString,
                response_deserializer=catalogo__pb2.ReservaResponse.FromString,
                _registered_method=True)
        self.LiberarEjemplar = channel.unary_unary(
                '/catalogo.Catalogo/LiberarEjemplar',
                request_serializer=catalogo__pb2.LiberarRequest.SerializeToString,
                response_deserializer=catalogo__pb2.LiberarResponse.FromString,
                _registered_method=True)
        self.ListarCatalogo = channel.unary_unary(
                '/catalogo.Catalogo/ListarCatalogo',
                request_serializer=catalogo__pb2.CatalogoRequest.SerializeToString,
                response_deserializer=catalogo__pb2.CatalogoResponse.FromString,
                _registered_method=True)
        self.ObtenerLibro = channel.unary_unary(
                '/catalogo.Catalogo/ObtenerLibro',
                request_serializer=catalogo__pb2.LibroRequest.SerializeToString,
                response_deserializer=catalogo__pb2.LibroDTO.FromString,
                _registered_method=True)


class CatalogoServicer:
    """Servicio gRPC para la gestion del catalogo de la biblioteca y reserva de ejemplares.
    """

    def ConsultarDisponibilidad(self, request, context):
        """Consulta la disponibilidad de ejemplares de un libro.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReservarEjemplar(self, request, context):
        """Reserva un ejemplar disponible de un libro especifico.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LiberarEjemplar(self, request, context):
        """Libera un ejemplar previamente prestado para devolverlo a estado disponible.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListarCatalogo(self, request, context):
        """RPCs adicionales para gestion completa del catalogo (Integrante 3)
        Lista los libros del catalogo con soporte para filtros opcionales.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObtenerLibro(self, request, context):
        """Obtiene el detalle completo de un libro incluyendo la lista de sus ejemplares.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CatalogoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ConsultarDisponibilidad': grpc.unary_unary_rpc_method_handler(
                    servicer.ConsultarDisponibilidad,
                    request_deserializer=catalogo__pb2.ConsultaRequest.FromString,
                    response_serializer=catalogo__pb2.ConsultaResponse.SerializeToString,
            ),
            'ReservarEjemplar': grpc.unary_unary_rpc_method_handler(
                    servicer.ReservarEjemplar,
                    request_deserializer=catalogo__pb2.ReservaRequest.FromString,
                    response_serializer=catalogo__pb2.ReservaResponse.SerializeToString,
            ),
            'LiberarEjemplar': grpc.unary_unary_rpc_method_handler(
                    servicer.LiberarEjemplar,
                    request_deserializer=catalogo__pb2.LiberarRequest.FromString,
                    response_serializer=catalogo__pb2.LiberarResponse.SerializeToString,
            ),
            'ListarCatalogo': grpc.unary_unary_rpc_method_handler(
                    servicer.ListarCatalogo,
                    request_deserializer=catalogo__pb2.CatalogoRequest.FromString,
                    response_serializer=catalogo__pb2.CatalogoResponse.SerializeToString,
            ),
            'ObtenerLibro': grpc.unary_unary_rpc_method_handler(
                    servicer.ObtenerLibro,
                    request_deserializer=catalogo__pb2.LibroRequest.FromString,
                    response_serializer=catalogo__pb2.LibroDTO.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'catalogo.Catalogo', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('catalogo.Catalogo', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Catalogo:
    """Servicio gRPC para la gestion del catalogo de la biblioteca y reserva de ejemplares.
    """

    @staticmethod
    def ConsultarDisponibilidad(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/catalogo.Catalogo/ConsultarDisponibilidad',
            catalogo__pb2.ConsultaRequest.SerializeToString,
            catalogo__pb2.ConsultaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReservarEjemplar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/catalogo.Catalogo/ReservarEjemplar',
            catalogo__pb2.ReservaRequest.SerializeToString,
            catalogo__pb2.ReservaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LiberarEjemplar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/catalogo.Catalogo/LiberarEjemplar',
            catalogo__pb2.LiberarRequest.SerializeToString,
            catalogo__pb2.LiberarResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListarCatalogo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/catalogo.Catalogo/ListarCatalogo',
            catalogo__pb2.CatalogoRequest.SerializeToString,
            catalogo__pb2.CatalogoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ObtenerLibro(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/catalogo.Catalogo/ObtenerLibro',
            catalogo__pb2.LibroRequest.SerializeToString,
            catalogo__pb2.LibroDTO.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
